ObservatorioBodega/ObservatorioBodega/Controllers/ColaboradoresController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Dapper;
using System.Data;
using MySql.Data.MySqlClient;
using System.Configuration;
using ObservatorioBodega.Models;

namespace ObservatorioBodega.Controllers
{
    public class ColaboradoresController : Controller
    {
        private IDbConnection Connection
        {
            get
            {
                string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                return new MySqlConnection(connectionString);
            }
        }
        // GET: Colaboradores
        public ActionResult Index()
        {
            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "SELECT * FROM Colaboradores";
                var contribuidores = dbConnection.Query<Colaborador>(query);
                return View(contribuidores);
            }
        }
        //FUNCION QUE PERMITE NAVEGAR AL FORMULARIO AL DAR CLICK EN EL BOTON
        public ActionResult Formulario()
        {
            return View("formAddCollaborators");
        }
        //FUNCION PARA INSERTAR LA DATA A LA BASE
        [HttpPost]
        public ActionResult InsertarDatos(Colaborador modelo)
        {
            if (ModelState.IsValid)
            {
                // Realiza la inserción de datos en la base de datos utilizando Dapper
                string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                using (var dbConnection = new MySqlConnection(connectionString))
                {
                    dbConnection.Open();
                    string query = "INSERT INTO Colaboradores (Usuario, Correo, Contrasena, Nombre, Apellido, Rol) VALUES (@Usuario, @Correo, @Contrasena, @Nombre, @Apellido, @Rol)";
                    dbConnection.Execute(query, modelo);
                }

                TempData["Exito"] = "Los datos se insertaron correctamente.";
                // Redirecciona a la página de éxito o a donde desees
                return RedirectToAction("Index");
            }

            return View("formAddCollaborators", modelo); // Muestra el formulario nuevamente en caso de errores
        }
        public ActionResult Eliminar(int id)
        {
            // Lógica para eliminar el dato con el ID proporcionado
            string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (var dbConnection = new MySqlConnection(connectionString))
            {
                dbConnection.Open();
                string query = "DELETE FROM Colaboradores WHERE ID = @ID";
                dbConnection.Execute(query, new { ID = id });
            }
            return RedirectToAction("Index"); // Redirige a la página principal o a donde desees
        }
        public ActionResult Editar(int id)
        {
            string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
            using (var dbConnection = new MySqlConnection(connectionString))
            {
                dbConnection.Open();
                var modelo = dbConnection.QueryFirstOrDefault<Colaborador>("SELECT * FROM Colaboradores WHERE ID = @ID", new { ID = id });

                if (modelo == null)
                {
                    return HttpNotFound();
                }

                // Agregar el ID al modelo
                //modelo.ID = id;
                return View("formEditCollaborators", modelo);
            }
        }
        [HttpPost]
        public ActionResult GuardarEdicion(Colaborador modelo)
        {
            if (ModelState.IsValid)
            {
                string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                using (var dbConnection = new MySqlConnection(connectionString))
                {
                    dbConnection.Open();
                    var query = "UPDATE Colaboradores SET Usuario = @Usuario, Correo = @Correo, Contrasena = @Contrasena, Nombre = @Nombre, Apellido = @Apellido, Rol = @Rol WHERE ID = @ID";
                    dbConnection.Execute(query, modelo);

                    TempData["Exito"] = "Los cambios se guardaron correctamente.";
                }
                return RedirectToAction("Index");
            }

            return View("formEditCollaborators");
        }
        //FUNCION PARA REGRESAR AL INDEX
        public ActionResult backToIndex()
        {
            return RedirectToAction("Index");
        }
    }
}

ObservatorioBodega/ObservatorioBodega/Views/Colaboradores/formAddCollaborators.cshtml
@model ObservatorioBodega.Models.Colaborador

@using (Html.BeginForm("InsertarDatos", "Colaboradores", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div style="display:flex; justify-content:flex-start">
        <a href="@Url.Action("backToIndex", "Colaboradores")">
            <button type="button" class="btn btn-danger">
                <i class="fa-solid fa-arrow-left" style="margin-right:5px"></i>Regresar
            </button>
        </a>
    </div>
    <div style="display:flex; justify-content:center">
        <div style="width:25%;">
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre)
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellido)
                @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Correo)
                @Html.TextBoxFor(model => model.Correo, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Usuario)
                @Html.TextBoxFor(model => model.Usuario, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Rol)
                @Html.TextBoxFor(model => model.Rol, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Contrasena)
                @Html.TextBoxFor(model => model.Contrasena, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div style="display:flex; justify-content:center; margin-top:15px">
        <button type="submit" class="btn btn-primary">Insertar Datos</button>
    </div>
}

ObservatorioBodega/ObservatorioBodega/Views/Colaboradores/formEditCollaborators.cshtml
@model ObservatorioBodega.Models.Colaborador

@{
    ViewBag.Title = "Editar Colaborador";
}

@using (Html.BeginForm("GuardarEdicion", "Colaboradores", FormMethod.Post))
{
    @Html.AntiForgeryToken()
    <div style="display:flex; justify-content:flex-start">
        <a href="@Url.Action("backToIndex", "Colaboradores")">
            <button type="button" class="btn btn-danger">
                <i class="fa-solid fa-arrow-left" style="margin-right:5px"></i>Regresar
            </button>
        </a>
    </div>
    <div style="display:flex; justify-content:center">
        <div style="width:25%;">

            @Html.HiddenFor(model => model.ID)
            <div class="form-group">
                <p>ID del registro: @Model.ID</p>
            </div>
            <div class="form-group">
                @Html.LabelFor(model => model.Nombre)
                @Html.TextBoxFor(model => model.Nombre, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Apellido)
                @Html.TextBoxFor(model => model.Apellido, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Correo)
                @Html.TextBoxFor(model => model.Correo, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Usuario)
                @Html.TextBoxFor(model => model.Usuario, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Rol)
                @Html.TextBoxFor(model => model.Rol, new { @class = "form-control" })
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Contrasena)
                @Html.TextBoxFor(model => model.Contrasena, new { @class = "form-control" })
            </div>
        </div>
    </div>
    <div style="display:flex; justify-content:center; margin-top:15px">
        <button type="submit" class="btn btn-primary">Editar</button>
    </div>
}

ObservatorioBodega/ObservatorioBodega/Views/Colaboradores/index.cshtml
@model IEnumerable<ObservatorioBodega.Models.Colaborador>

<h2>Colaboradores</h2>
<div style="display:flex; justify-content:flex-end; margin-bottom:15px">
    <a href="@Url.Action("Formulario", "Colaboradores")">
        <button type="button" class="btn btn-primary" style="width:175px">
            <i class="fa-solid fa-plus" style="margin-right:5px"></i>
            Agregar
        </button>
    </a>
</div>
<table class="table table-striped">
    <thead>
        <tr>
            <th>ID</th>
            <th>Usuario</th>
            <th>Correo</th>
            <th>Contraseña</th>
            <th>Nombre</th>
            <th>Apellido</th>
            <th>Rol</th>
        </tr>
    </thead>
    <tbody>
        @foreach (var contribuidor in Model)
        {
            <tr>
                <td>@contribuidor.ID</td>
                <td>@contribuidor.Usuario</td>
                <td>@contribuidor.Correo</td>
                <td>@contribuidor.Contrasena</td>
                <td>@contribuidor.Nombre</td>
                <td>@contribuidor.Apellido</td>
                <td>@contribuidor.Rol</td>
                <td>
                    <button type="button" class="btn" style="background-color: #96F2B8 "
                            onclick="editarData(@contribuidor.ID)">
                        <i class="fa-solid fa-pen"></i>
                    </button>
                    <button type="button" class="btn" style="background-color: #FF2819 "
                            onclick="confirmarEliminacion(@contribuidor.ID)">
                        <i class="fa-solid fa-trash"></i>
                    </button>
                </td>
            </tr>
        }
    </tbody>
</table>
<script>
    function confirmarEliminacion(ID) {
        if (confirm("¿Estás seguro de que deseas eliminar este dato?")) {
            // Redirigir a la acción de eliminación si el usuario confirma
            window.location.href = '@Url.Action("Eliminar", "Colaboradores")/' + ID;
        }
    }
    function editarData(ID) {
            window.location.href = '@Url.Action("Editar", "Colaboradores")/' + ID;
    }
</script>