ObservatorioBodega/ObservatorioBodega/Models/Documento.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace ObservatorioBodega.Models
{
    public class Documentos
    {
        public int ID { get; set; }
        public string Titulo { get; set; }
        public int ColaboradorID { get; set; }
        public string Nombre { get; set; } // Propiedad para el nombre del colaborador
        public string Apellido { get; set; } // Propiedad para el apellido del colaborador
        public DateTime Fecha { get; set; }
        public string URL { get; set; }

    }

}

ObservatorioBodega/ObservatorioBodega/Controllers/DocumentosController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.IO; //para pdfs
using Dapper;
using System.Data;
using System.Net; 
using MySql.Data.MySqlClient;
using System.Configuration;
using ObservatorioBodega.Models;


namespace ObservatorioBodega.Controllers
{
    public class DocumentosController : Controller
    {
        private IDbConnection Connection
        {
            get
            {
                string connectionString = ConfigurationManager.ConnectionStrings["DefaultConnection"].ConnectionString;
                return new MySqlConnection(connectionString);
            }
        }
        // GET: Documentos
        public ActionResult Index()
        {
            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "SELECT D.*, C.Nombre, C.Apellido FROM Documentos D " +
                "INNER JOIN Colaboradores C ON D.ColaboradorID = C.ID";
                var documentos = dbConnection.Query<Documentos>(query);
                return View(documentos);
            }
        }

        // GET: Documentos/Details/
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "SELECT * FROM Documentos WHERE ID = @Id";
                var documento = dbConnection.QueryFirstOrDefault<Documentos>(query, new { Id = id });

                if (documento == null)
                {
                    return HttpNotFound();
                }

                return View(documento);
            }
        }

        // GET: Documentos/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Documentos/Create
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "ID,Titulo,ColaboradorID,URL")] Documentos documento, HttpPostedFileBase pdfFile)
        {
            if (ModelState.IsValid)
            {
                if (pdfFile != null && pdfFile.ContentLength > 0)
                {
                    // Validación del nombre del archivo
                    string fileName = Path.GetFileName(pdfFile.FileName);
                    if (!IsValidFileName(fileName))
                    {
                        ModelState.AddModelError("pdfFile", "El nombre del archivo no es válido.");
                        return View(documento);
                    }

                    // Guarda el archivo PDF en el servidor
                    string serverPath = Server.MapPath("~/Uploads/PDFs/");
                    string fullPath = Path.Combine(serverPath, fileName);

                    // Verifica si el archivo ya existe
                    if (System.IO.File.Exists(fullPath))
                    {
                        ModelState.AddModelError("pdfFile", "El archivo ya existe.");
                        return View(documento);
                    }

                    pdfFile.SaveAs(fullPath);

                    // Asigna la ruta absoluta al campo URL
                    documento.URL = Url.Content("/Uploads/PDFs/" + fileName);

                    using (IDbConnection dbConnection = Connection)
                    {
                        dbConnection.Open();
                        string query = "INSERT INTO Documentos (Titulo, ColaboradorID, URL) VALUES (@Titulo, @ColaboradorID, @URL)";
                        dbConnection.Execute(query, documento);
                    }

                    return RedirectToAction("Index");
                }

                return View(documento);
            }

            return View(documento);
        }


        // GET: Documentos/Edit/
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "SELECT * FROM Documentos WHERE ID = @Id";
                var documento = dbConnection.QueryFirstOrDefault<Documentos>(query, new { Id = id });

                if (documento == null)
                {
                    return HttpNotFound();
                }

                return View(documento);
            }
        }

        // POST: Documentos/Edit/
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "ID,Titulo,ColaboradorID,URL")] Documentos documento)
        {
            if (ModelState.IsValid)
            {
                using (IDbConnection dbConnection = Connection)
                {
                    dbConnection.Open();
                    string query = "UPDATE Documentos SET Titulo = @Titulo, ColaboradorID = @ColaboradorID, URL = @URL WHERE ID = @ID";
                    dbConnection.Execute(query, documento);
                }

                return RedirectToAction("Index");
            }

            return View(documento);
        }

        // GET: Documentos/Delete/
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "SELECT * FROM Documentos WHERE ID = @Id";
                var documento = dbConnection.QueryFirstOrDefault<Documentos>(query, new { Id = id });

                if (documento == null)
                {
                    return HttpNotFound();
                }

                return View(documento);
            }
        }

        // POST: Documentos/Delete/
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "DELETE FROM Documentos WHERE ID = @Id";
                dbConnection.Execute(query, new { Id = id });
            }

            return RedirectToAction("Index");
        }

        // GET: Documentos/ViewPDF/
        public ActionResult ViewPDF(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }

            using (IDbConnection dbConnection = Connection)
            {
                dbConnection.Open();
                string query = "SELECT URL FROM Documentos WHERE ID = @Id";
                string pdfUrl = dbConnection.QueryFirstOrDefault<string>(query, new { Id = id });

                if (pdfUrl == null)
                {
                    return HttpNotFound();
                }
                
                // Abre el PDF en una nueva ventana utilizando JavaScript
                return Content($"<script>window.open('{pdfUrl}','_blank');</script>");
            }
        }
        // Función para validar el nombre del archivo
        private bool IsValidFileName(string fileName)
        {
            // Puedes implementar tus reglas de validación aquí
            // Por ejemplo, verificar la longitud máxima y caracteres especiales no permitidos
            if (string.IsNullOrWhiteSpace(fileName) || fileName.Length > 100 || fileName.Contains(".."))
            {
                return false;
            }
            return true;
        }

    }
}

ObservatorioBodega/ObservatorioBodega/Views/Documentos/Create.cshtml
@model ObservatorioBodega.Models.Documentos

@{
    ViewBag.Title = "Create";
}

<h2>Registrar documento</h2>

@using (Html.BeginForm("Create", "Documentos", FormMethod.Post, new { enctype = "multipart/form-data" }))
{
    @Html.AntiForgeryToken()

    <div class="form-horizontal">
        <h4>Documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColaboradorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColaboradorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColaboradorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.Label("PDF", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input type="file" name="pdfFile" />
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Registrar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar a lista", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ObservatorioBodega/ObservatorioBodega/Views/Documentos/Delete.cshtml
@model ObservatorioBodega.Models.Documentos

@{
    ViewBag.Title = "Delete";
}

<h2>Eliminar</h2>

<h3>Seguro que desea eliminar este registro?</h3>
<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColaboradorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColaboradorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Eliminar" class="btn btn-default" /> |
            @Html.ActionLink("Regresar a lista", "Index")
        </div>
    }
</div>

ObservatorioBodega/ObservatorioBodega/Views/Documentos/Details.cshtml
@model ObservatorioBodega.Models.Documentos

@{
    ViewBag.Title = "Details";
}

<h2>Detalles</h2>

<div>
    <h4>Documento</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Titulo)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Titulo)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ColaboradorID)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ColaboradorID)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.URL)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.URL)
        </dd>

    </dl>
</div>
<p>
    @Html.ActionLink("Editar", "Edit", new { id = Model.ID }) |
    @Html.ActionLink("Regresar a la lista", "Index")
</p>

ObservatorioBodega/ObservatorioBodega/Views/Documentos/Edit.cshtml
@model ObservatorioBodega.Models.Documentos

@{
    ViewBag.Title = "Edit";
}

<h2>Editar</h2>


@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Documento</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.ID)

        <div class="form-group">
            @Html.LabelFor(model => model.Titulo, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Titulo, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Titulo, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ColaboradorID, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ColaboradorID, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ColaboradorID, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.URL, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.URL, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.URL, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Guardar" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Regresar al listado", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

ObservatorioBodega/ObservatorioBodega/Views/Documentos/Index.cshtml
@model IEnumerable<ObservatorioBodega.Models.Documentos>

@{
    ViewBag.Title = "Index";
}

<h2>Documentos</h2>

<div style="display:flex; justify-content:flex-end; margin-bottom:15px">

    <a href="@Url.Action("Create")" style="width:175px">
        <button type="button" class="btn btn-primary" style="width:175px">
            <i class="fa-solid fa-plus" style="margin-right:5px"></i>
            Agregar
        </button>

    </a>

</div>


<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Titulo)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Nombre)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Fecha)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.URL)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Titulo)
            </td>
            <td>
                @item.Nombre @item.Apellido
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Fecha)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.URL)
            </td>
            <td>
                <a href="@Url.Action("Edit", new { id = item.ID })" style="width: 175px">
                    <button type="button" class="btn" style="background-color: #96F2B8; color: black; margin-right: 10px">
                        <i class="fa-solid fa-pen" style="margin-right: 10px;"></i>
                        <!-- Edit -->
                    </button>
                </a>
                <a href="javascript:void(0);" onclick="openPdfInNewTab(@item.ID, event)" class="btn btn-info">Ver PDF</a>


                <a href="@Url.Action("Details", new { id = item.ID })" style="width: 175px">
                    <button type="button" class="btn" style="background-color: #FFFF00; color: black; margin-right: 10px ">
                        <i class="fa-solid fa-info" style="margin-right: 10px"></i>
                        <!-- Details -->
                    </button>
                </a>

                <a href="@Url.Action("Delete", new { id = item.ID })" style="width: 175px">
                    <button type="button" class="btn" style="background-color: #FF2819; color: black; margin-right: 10px">
                        <i class="fa-solid fa-trash" style="margin-right: 10px"></i>
                        <!-- Delete -->
                    </button>
                </a>
            </td>

        </tr>
    }

</table>

<script>
    function openPdfInNewTab(id, event) {
    // Construye la URL del controlador que abrirá el PDF en una nueva ventana
    var pdfUrl = '@Url.Action("ViewPDF", "Documentos")/' + id;

    // Previene la acción por defecto del enlace
    event.preventDefault();

    // Abre el PDF en una nueva ventana
    window.open(pdfUrl, '_blank');
    }

</script>